on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verify installation
        run: |
          echo "y" | sudo bash installer.sh
          if [ -f "/usr/local/bin/translate" ] 
          then
              echo "Binary installed successfully."
          else
              echo "Binary could not be installed."
              throw "Error: File /usr/local/bin/pages does not exists."
          fi
      - name: Verify API validity
        run: |
          x=$(translate en de Hello World)
          if [[ "$x" == "Hallo Welt" ]]; then
            echo "API valid."
          else
            throw "API no longer valid."
          fi
